language: node_js

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - node_modules

node_js:
  #- '6'
  #- '7'
  - '8'
  - '9'
  - '10'
  - '11'

stages:
  - test
  - name: deploy
    if: branch = travis-test AND type = push

before_script: npm run build
script:
  - npm run lint
  - npm run coverage

jobs:
  include:
    - stage: test
      after_success: 'echo "Submitting (fake) coverage for Node Version $TRAVIS_NODE_VERSION"'
    - stage: deploy
      script: skip
      after_success: skip
      after_script:
        - echo "would normally deploy now..."
        - echo "$NODE_VERSION_TO_SUBMIT"
