language: node_js

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - node_modules

node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

env:
  - NODE_VERSION_TO_SUBMIT=10

stages:
  - test
  - name: deploy
    if: branch = travis-test AND type = push

before_script: npm run build
script:
  - npm run lint
  - npm run coverage
after_success:
  - echo "$TRAVIS_NODE_VERSION"
  - 'if [ "$TRAVIS_NODE_VERSION" = "10" ]; then echo "yes"; else echo "nope"; fi'
  - 'if [ "$TRAVIS_NODE_VERSION" = "$NODE_VERSION_TO_SUBMIT" ]; then echo "yes"; else echo "nope"; fi'
  - '[ "$SUBMIT_COVERAGE" -eq "1" ] && echo "Submitting coverage report" && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'

jobs:
  include:
    - stage: deploy
      node_js: '10'
      script: skip
      after_success: skip
      after_script:
        - echo "kind of working..."
        - echo "$NODE_VERSION_TO_SUBMIT"
