language: node_js

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - node_modules

node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  #- '11' # Runs the coverage report (added below)

before_script: npm run build
script:
  - npm run lint
  - npm run coverage

jobs:
  include:
    - stage: test
      node_js: '11'
      env: 'SUBMIT_COVERAGE_REPORT=1' # Just for the Travis UI
      after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
    - stage: deploy
      node_js: '11'
      script: skip
      after_script:
        - echo "would normally deploy now..."
        - echo "$NODE_VERSION_TO_SUBMIT"

stages:
  - test
  - name: deploy
    if: branch = travis-test AND type = push
